//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafepressUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAFEPRESS_EMAIL {
            get {
                return ((string)(this["CAFEPRESS_EMAIL"]));
            }
            set {
                this["CAFEPRESS_EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAFEPRESS_PASS {
            get {
                return ((string)(this["CAFEPRESS_PASS"]));
            }
            set {
                this["CAFEPRESS_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login success.")]
        public string LOGIN_SUCCESS {
            get {
                return ((string)(this["LOGIN_SUCCESS"]));
            }
            set {
                this["LOGIN_SUCCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login failed.")]
        public string LOGIN_FAILED {
            get {
                return ((string)(this["LOGIN_FAILED"]));
            }
            set {
                this["LOGIN_FAILED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Template\\\\")]
        public string TEMPLATE_PATH {
            get {
                return ((string)(this["TEMPLATE_PATH"]));
            }
            set {
                this["TEMPLATE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("success.txt")]
        public string SUCCESS_FILE {
            get {
                return ((string)(this["SUCCESS_FILE"]));
            }
            set {
                this["SUCCESS_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("failed.txt")]
        public string FAILED_FILE {
            get {
                return ((string)(this["FAILED_FILE"]));
            }
            set {
                this["FAILED_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPLOADED\\\\")]
        public string UPLOADED_LOGO {
            get {
                return ((string)(this["UPLOADED_LOGO"]));
            }
            set {
                this["UPLOADED_LOGO"] = value;
            }
        }
    }
}
