//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpload.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Platform\\ViralStyle\\Shirts")]
        public string ViralStyle_Mockup_Path {
            get {
                return ((string)(this["ViralStyle_Mockup_Path"]));
            }
            set {
                this["ViralStyle_Mockup_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Platform\\ViralStyle\\accounts.txt")]
        public string ViralStyle_Account_Path {
            get {
                return ((string)(this["ViralStyle_Account_Path"]));
            }
            set {
                this["ViralStyle_Account_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Platform\\ViralStyle\\Products\\Product.json")]
        public string ViralStyle_Product_Path {
            get {
                return ((string)(this["ViralStyle_Product_Path"]));
            }
            set {
                this["ViralStyle_Product_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string SHOW_MOCKUP {
            get {
                return ((string)(this["SHOW_MOCKUP"]));
            }
            set {
                this["SHOW_MOCKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Platform\\ViralStyle\\Templates\\")]
        public string TEMPLATE_PATH {
            get {
                return ((string)(this["TEMPLATE_PATH"]));
            }
            set {
                this["TEMPLATE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Completed\\")]
        public string COMPLETED_PATH {
            get {
                return ((string)(this["COMPLETED_PATH"]));
            }
            set {
                this["COMPLETED_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMAIL {
            get {
                return ((string)(this["EMAIL"]));
            }
            set {
                this["EMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
            set {
                this["PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string MAX_COLORS {
            get {
                return ((string)(this["MAX_COLORS"]));
            }
            set {
                this["MAX_COLORS"] = value;
            }
        }
    }
}
